package bessant.chris.test.app;

import java.util.Random;

/**
 * This is purely a simple test class. It's purpose is only to create a Maven project which
 * can be build by Bamboo and have stats generated by Sonar. 
 */

public class App 
{

	private static String[] quote = new String[5];
	
    public static void main( String[] args )
    {
        App a = new App();
        int q = selectQuote();
        System.out.println(a.getQuote(q));
    }
    
    public static int selectQuote() {
    	Random randomGenerator = new Random();
    	return randomGenerator.nextInt(5); 
    }
    
    public String getQuote(int q) {	
    	
    	quote[0] = "In the beginning there was nothing, which exploded - Terry Pratchet";
    	quote[1] = "Nothing happens until something moves - Albert Einstein";
    	quote[2] = "Photons have mass? I didn’t even know they were Catholic - Woody Allen";
    	quote[3] = "No, this trick won't work... How on earth are you ever going to explain in terms of chemistry and physics so important a biological phenomenon as first love? - Albert Einstein";
    	quote[4] = "Physics isn't the most important thing. Love is - Richard P Feynman";
    	
    	return quote[q];
    }
    
}
